import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

const lightColors = {
  primary: '#6366f1',
  onPrimary: '#ffffff',
  primaryContainer: '#e0e7ff',
  onPrimaryContainer: '#1e1b4b',
  secondary: '#f59e0b',
  onSecondary: '#ffffff',
  secondaryContainer: '#fef3c7',
  onSecondaryContainer: '#92400e',
  tertiary: '#10b981',
  onTertiary: '#ffffff',
  tertiaryContainer: '#d1fae5',
  onTertiaryContainer: '#064e3b',
  error: '#ef4444',
  onError: '#ffffff',
  errorContainer: '#fecaca',
  onErrorContainer: '#991b1b',
  background: '#fafafa',
  onBackground: '#1f2937',
  surface: '#ffffff',
  onSurface: '#1f2937',
  surfaceVariant: '#f3f4f6',
  onSurfaceVariant: '#6b7280',
  outline: '#d1d5db',
  outlineVariant: '#e5e7eb',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#374151',
  inverseOnSurface: '#f9fafb',
  inversePrimary: '#a5b4fc',
  elevation: {
    level0: 'transparent',
    level1: '#ffffff',
    level2: '#f9fafb',
    level3: '#f3f4f6',
    level4: '#f1f5f9',
    level5: '#f8fafc',
  },
};

const darkColors = {
  primary: '#a5b4fc',
  onPrimary: '#1e1b4b',
  primaryContainer: '#3730a3',
  onPrimaryContainer: '#e0e7ff',
  secondary: '#fbbf24',
  onSecondary: '#92400e',
  secondaryContainer: '#d97706',
  onSecondaryContainer: '#fef3c7',
  tertiary: '#34d399',
  onTertiary: '#064e3b',
  tertiaryContainer: '#059669',
  onTertiaryContainer: '#d1fae5',
  error: '#f87171',
  onError: '#991b1b',
  errorContainer: '#dc2626',
  onErrorContainer: '#fecaca',
  background: '#111827',
  onBackground: '#f9fafb',
  surface: '#1f2937',
  onSurface: '#f9fafb',
  surfaceVariant: '#374151',
  onSurfaceVariant: '#d1d5db',
  outline: '#6b7280',
  outlineVariant: '#4b5563',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#f9fafb',
  inverseOnSurface: '#374151',
  inversePrimary: '#6366f1',
  elevation: {
    level0: 'transparent',
    level1: '#1f2937',
    level2: '#374151',
    level3: '#4b5563',
    level4: '#6b7280',
    level5: '#9ca3af',
  },
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: lightColors,
  fonts: {
    ...MD3LightTheme.fonts,
    default: {
      fontFamily: 'Cairo-Regular',
    },
    displayLarge: {
      fontFamily: 'Cairo-Bold',
      fontSize: 57,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'Cairo-Bold',
      fontSize: 45,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'Cairo-Bold',
      fontSize: 36,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'Cairo-Bold',
      fontSize: 32,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'Cairo-SemiBold',
      fontSize: 28,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'Cairo-SemiBold',
      fontSize: 24,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: 'Cairo-SemiBold',
      fontSize: 22,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'Cairo-Medium',
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'Cairo-Medium',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: 'Cairo-Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'Cairo-Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'Cairo-Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: 'Cairo-Medium',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'Cairo-Medium',
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'Cairo-Medium',
      fontSize: 11,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: darkColors,
  fonts: lightTheme.fonts,
};

export const theme = lightTheme;

